Controllers/SingleForumController.cs
using System;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using _931901.kuznetsov.semyon.lab2._6.Data;
using _931901.kuznetsov.semyon.lab2._6.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _931901.kuznetsov.semyon.lab2._6.Controllers
{
    public class SingleForumController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> UserManager;



        public SingleForumController(ApplicationDbContext context, UserManager<IdentityUser> manager)
        {
            _context = context;
            UserManager = manager;
        }
        public async Task<IActionResult> SingleForums()
        {
            var topics = _context.topicCreatorModels;
           
                ViewBag.ReplCount = _context.Topics.CountAsync().Result;
           
            return View(await topics.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(new TopicCreatorModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(TopicCreatorViewModel model)
        {
            if (!ModelState.IsValid) return View();

            CultureInfo culture = new("en-US");
            TopicCreatorModel topic = new();
            topic.Title = model.Title;
            topic.Author = UserManager.GetUserName(User);
            topic.CreateDate = DateTime.Now.ToString("dddd, dd MMMM yyyy HH:mm:ss", culture);

            await _context.topicCreatorModels.AddAsync(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(SingleForums));
        }
    }
}

Controllers/SingleTopicController.cs
using System;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using _931901.kuznetsov.semyon.lab2._6.Data;
using _931901.kuznetsov.semyon.lab2._6.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _931901.kuznetsov.semyon.lab2._6.Controllers
{
    public class SingleTopicController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> UserManager;

        public SingleTopicController(ApplicationDbContext context, UserManager<IdentityUser> manager)
        {
            _context = context;
            UserManager = manager;
        }

        public async Task<IActionResult> Index()
        {
            var topics = _context.Topics;
            return View(await topics.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(new TopicModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(TopicViewModel model)
        {
            if (!ModelState.IsValid) return View();

            CultureInfo culture = new CultureInfo("en-US");
            TopicModel topic = new TopicModel();
            topic.Title = model.Title;
            topic.Text = model.Text;
            topic.Author = UserManager.GetUserName(User);
            topic.CreateDate = DateTime.Now.ToString("dddd, dd MMMM yyyy HH:mm:ss", culture);

            if (model.Image1 != null)
                topic.Image1 = AddImageInDatabase(model.Image1);

            if (model.Image2 != null)
                topic.Image2 = AddImageInDatabase(model.Image2);

            if (model.Image3 != null)
                topic.Image3 = AddImageInDatabase(model.Image3);

            await _context.Topics.AddAsync(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private byte[] AddImageInDatabase(IFormFile file)
        {
            using var binaryReader = new BinaryReader(file.OpenReadStream());
            var imageData = binaryReader.ReadBytes((int) file.Length);

            return imageData;
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, TopicModel model)
        {
            if (id == null) return NotFound();

            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();
            if (!ModelState.IsValid) return View(model);

            CultureInfo culture = new CultureInfo("en-US");
            topic.Title = model.Title;
            topic.Text = model.Text;
            topic.EditDate = DateTime.Now.ToString("dddd, dd MMMM yyyy HH:mm:ss", culture);
            _context.Entry(topic).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();

            _context.Topics.Remove(topic);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteImg(int? id, int? imgIndex)
        {
            if (id == null) return NotFound();
            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();

            switch (imgIndex)
            {
                case 1:
                    topic.Image1 = null;
                    break;
                case 2:
                    topic.Image2 = null;
                    break;
                default:
                    topic.Image3 = null;
                    break;
            }

            _context.Entry(topic).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Attach(int? id)
        {
            if (id == null) return NotFound();

            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Attach(TopicViewModel model, int? id)
        {
            if (id == null) return NotFound();

            var topic = await _context.Topics.FindAsync(id);
            if (topic == null) return NotFound();

            if (model.Image1 != null)
                topic.Image1 = AddImageInDatabase(model.Image1);

            if (model.Image2 != null)
                topic.Image2 = AddImageInDatabase(model.Image2);

            if (model.Image3 != null)
                topic.Image3 = AddImageInDatabase(model.Image3);

            _context.Entry(topic).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/SingleForum/Create.cshtml
@model _931901.kuznetsov.semyon.lab2._6.Models.TopicCreatorModel
@{ ViewData["Title"] = "Create"; }

<h2>Create Reply</h2>

<div class="blog-post-editor">
    <form asp-action="Create">
        <div class="form-horizontal">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <b>
                    <label asp-for="Title" class="col-md-2 control-label"></label>
                </b>
                <div class="col-md-10">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-dark" />
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="SingleForums">Back to topic creator</a>
</div>

Views/SingleForum/SingleForums.cshtml
@model IEnumerable<_931901.kuznetsov.semyon.lab2._6.Models.TopicCreatorModel>
@{ ViewData["Title"] = "SingleForum"; }
<h2>Forum 1</h2>
<p>First forum description</p>

<p>
    <a asp-action="Create">Create new topic</a>
</p>


<table class="table table-striped">
    <tbody>
        @foreach (var item in Model.OrderBy(x => x.Id))
        {
<tr>
    <td>
        <a asp-controller="SingleTopic" asp-action="Index" style="font-size: 1.3em">@Html.DisplayFor(modelItem => item.Title)</a><br />
        @Html.DisplayFor(modelItem => item.Author),
        @Html.DisplayFor(modelItem => item.CreateDate)
    </td>
    <td style="width: 100px">
        @ViewBag.ReplCount replies
    </td>
    <td style="width: 220px">
        @Html.DisplayFor(modelItem => item.Author)<br />
        @Html.DisplayFor(modelItem => item.CreateDate)
    </td>
</tr>
}
    </tbody>
</table>