Models/ViewModels/ForumCategory.cs
using System.ComponentModel.DataAnnotations;

namespace _931901.kuznetsov.semyon.lab2._6.Models
{
    public class ForumCategory
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
    }
}

Controllers/ForumCategorysController.cs
using System.Threading.Tasks;
using _931901.kuznetsov.semyon.lab2._6.Data;
using _931901.kuznetsov.semyon.lab2._6.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _931901.kuznetsov.semyon.lab2._6.Controllers
{
    public class ForumCategorysController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumCategorysController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ForumCategories.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(new ForumCategory());
        }

        [HttpPost]
        public async Task<IActionResult> Create(ForumCategory model)
        {
            if (!ModelState.IsValid) return View(model);
            await _context.ForumCategories.AddAsync(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var forumCategory = await _context.ForumCategories.FindAsync(id);
            if (forumCategory == null) return NotFound();

            return View(forumCategory);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var forumCategory = await _context.ForumCategories.FindAsync(id);
            if (forumCategory == null) return NotFound();

            return View(forumCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, ForumCategory model)
        {
            if (id == null) return NotFound();
            var forumCategory = await _context.ForumCategories.FindAsync(id);
            if (forumCategory == null) return NotFound();

            if (!ModelState.IsValid) return View(model);
            forumCategory.Name = model.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var forumCategory = await _context.ForumCategories.FindAsync(id);
            if (forumCategory == null) return NotFound();

            _context.ForumCategories.Remove(forumCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/ForumCategorys/Create.cshtml
@model _931901.kuznetsov.semyon.lab2._6.Models.ForumCategory

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Forum Category</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div class="form-group">
                <b>
                    <label asp-for="Name" class="control-label"></label>
                </b>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ForumCategorys/Details.cshtml
@model _931901.kuznetsov.semyon.lab2._6.Models.ForumCategory;
@{ ViewData["Title"] = "Details"; }

<h2>Details</h2>
<div>
    <h4>Forum Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ForumCategorys/Edit.cshtml
@model _931901.kuznetsov.semyon.lab2._6.Models.ForumCategory;

@{ ViewData["Title"] = "Edit"; }

<h2>Edit</h2>

<h4>Forum Category</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <b>
                    <label asp-for="Name" class="control-label"></label>
                </b>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-dark"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ForumCategorys/Index.cshtml
@model IEnumerable<_931901.kuznetsov.semyon.lab2._6.Models.ForumCategory>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New File_System</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    @foreach (var item in Model.OrderBy(x => x.Name))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-controller="ForumCategorys" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="ForumCategorys" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-controller="ForumCategorys" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>